<a href="https://colab.research.google.com/github/Rukshana-S/hiver-spotify-ai-support-agent/blob/main/01_spotify_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

path = "/content/drive/MyDrive/Hiver_Spotify_AI/data/twcs.csv"

df = pd.read_csv(path)

In [3]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 7 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   tweet_id                 1048575 non-null  int64
 1   author_id                1048575 non-null  object
 2   inbound                  1048575 non-null  bool
 3   created_at               1048575 non-null  object
 4   text                     1048575 non-null  object
 5   response_tweet_id        683860 non-null   object
 6   in_response_to_tweet_id  767999 non-null   float64
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 49.0+ MB

In [5]:
df.isnull().sum()

tweet_id                        0
author_id                       0
inbound                         0
created_at                      0
text                            0
response_tweet_id          364715
in_response_to_tweet_id    280576
dtype: int64

In [6]:
df.to_csv(
    "/content/drive/MyDrive/Hiver_Spotify_AI/processed/raw_loaded.csv",
    index=False
)